class Parser:

    """Analyzes the syntactic structure of a token sequence generated by the
    Lexer using  k>1 lookahead tokens
    """

    def __init__(self, lexer, num_lts):
        """
        :lts: lookahead tokens
        :num_lts: number of lookahead tokens
        :lt_idx: lookahead token index

        """
        self.lexer = lexer
        self.num_lts = num_lts
        self.lts = [None] * self.num_lts
        self.lt_idx = 0
        for _ in range(self.num_lts):
            self.next_token()

    def next_token(self):
        """fills next position in the lookahead tokenlist with token

        :returns: None

        """
        self.lts[self.lt_idx] = self.lexer.next_token()
        self.lt_idx = (self.lt_idx + 1) % self.num_lts

    def LT(self, i):
        """Lookahead Token

        :returns: find out token looking ahead i tokens
        """
        return self.lts[(self.lt_idx + i - 1) % self.num_lts]

    def LTT(self, i):
        """Lookahead tokentype

        :returns: find out type locking ahead i tokens
        """
        return self.LT(i).type

    def match(self, tt):
        """Check if t is the next token in the lexer to match

        :tt: possibly matching tokentype
        :returns: TODO

        """
        if (self.LTT(1) == tt):
            self.next_token()
        else:
            raise SyntaxError(tt, self.LTT(1))
