# resources: https://github.com/qutebrowser/qutebrowser/blob/master/.github/workflows/nightly.yml
# https://github.com/JackMcKew/pyinstaller-action-windows,
# https://github.com/Nuitka/Nuitka-Action
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/svenstaro/upload-release-action

name: Package Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: PicoC-Compiler-Linux
          - os: windows-2019
            artifact_name: PicoC-Compiler-Windows
          - os: macos-2019
            artifact_name: PicoC-Compiler-MacOs

    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: "master"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements.txt

      - name: Run Pyinstaller
        run: pyinstaller src/main.spec

      # - name: Tar files
      #   run: tar -cvf picoc_compiler.tar dist/picoc_compiler

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/picoc_compiler
