# resources: https://github.com/qutebrowser/qutebrowser/blob/master/.github/workflows/nightly.yml
# https://github.com/JackMcKew/pyinstaller-action-windows,
# https://github.com/Nuitka/Nuitka-Action
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/svenstaro/upload-release-action
# https://blog.knoldus.com/manual-trigger-in-github-actions/

name: create executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    tags:
      - "*"

permissions:
  contents: write


jobs:
  build:
    name: Package for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: PicoC-Compiler-Linux
            asset_name: picoc_compiler_linux_amd64.tar.gz
          - os: windows-latest
            artifact_name: PicoC-Compiler-Windows
            asset_name: picoc_compiler_windows_amd64.tar.gz
          - os: macos-latest  # macos-12
            artifact_name: PicoC-Compiler-MacOs
            asset_name: picoc_compiler_macos_amd64.tar.gz

    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: "master"

      - name: Get Documentation
        run: |
          cd src
          git clone https://github.com/matthejue/Bachelorarbeit_Dokumentation_out --depth=1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements.txt

      - name: Run Pyinstaller
        run: pyinstaller src/main.spec

      - name: Tar files
        run: |
          cd dist
          tar -zcvf ${{ matrix.asset_name }} picoc_compiler

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ./dist/${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./PicoC-Compiler-Linux/picoc_compiler_linux_amd64.tar.gz
          ./PicoC-Compiler-Windows/picoc_compiler_windows_amd64.tar.gz
          ./PicoC-Compiler-MacOs/picoc_compiler_macos_amd64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
