# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, new_architecture ]
  pull_request:
    branches: [ master, new_architecture ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      # run: sudo apt install python3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "${GITHUB_WORKSPACE}/src/requirements.txt" ]; then pip install -r "${GITHUB_WORKSPACE}/src/requirements.txt"; fi
    - name: Test with Shellscript
      run: |
        "${GITHUB_WORKSPACE}/run_tests.sh" "79"
