name: run system tests

on:
  push:
    branches: [ master, new_architecture ]
  pull_request:
    branches: [ master, new_architecture ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd ${GITHUB_WORKSPACE}
        make install-dependencies
    - name: Install RETI-Interpeter
      run: |
        git clone https://github.com/matthejue/RETI-Interpreter.git
        cd RETI-Interpreter
        make install-linux-local
    - name: Test with Shellscript
      run: |
        cd ${GITHUB_WORKSPACE}
        ./run_sys_tests.sh 79

