name: run system tests

on:
  push:
    branches: [ master, new_architecture ]
  pull_request:
    branches: [ master, new_architecture ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "${GITHUB_WORKSPACE}/requirements.txt" ]; then pip install -r "${GITHUB_WORKSPACE}/requirements.txt"; fi
    - name: Install RETI-Interpeter
      run: |
        git clone https://github.com/matthejue/RETI-Interpreter.git
        cd RETI-Interpreter
        make install-linux-local
    - name: Test with Shellscript
      run: |
        "${GITHUB_WORKSPACE}/run_sys_tests.sh" "79"
